version: '3.4'

services:
  db:
    image: my/db/sql-server
    build:
      context: .
      dockerfile: data/Dockerfile
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "p@ssword123456789!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
     - mssqldata:/var/opt/mssql

volumes:
  mssqldata: